openapi: '3.0.3'
info:
  title: Beta Link - Auth µService API
  version: '0.1'
servers:
  - url: https://api.auth.betalink.com/
paths:
  /login:
    post:
      summary: Authenticate the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginData"
            example:
              username: "john.doe@gmail.com"
              password: "12345678"
      responses:
        "200":
          description: The user has been successfully authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAccessData"
        "400":
          description: The request payload is missing required fields
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
              example:
                error: "Bad Request"
                message: "The payload is missing some required fields."
                missingFields: ["email", "password"]
        "401":
          description: The credentials do not match any account.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                error: "Unauthorized"
                message: "The credentials do not match any account."
        "403":
          description: The user's account is not verified.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                error: "Forbidden"
                message: "Account not verified. Please validate your email."
        "429":
          description: Too many requests. Please try again later.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Too Many Requests"
                message: "You have made too many requests in the past 5 minutes. Please try again later."
        "500":
          description: A server-side error occurred during login.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                error: "Internal Server Error"
                message: "An error occurred while processing your request. Please try again later."
  /login/external/{provider}:
    post:
      summary: Authenticate the user via an external provider.
      parameters:
        - $ref: "#/components/parameters/ExternalProvider"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExternalLoginData"
      responses:
        "200":
          description: The user has been successfully authenticated with the external provider
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAccessData"
        "400":
          description: The request payload is missing required fields or is malformed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
              example:
                error: "Bad Request"
                message: "The payload is missing some required fields."
                missingFields: ["token"]
        "401":
          description: The external token is invalid or expired
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                error: "Unauthorized"
                message: "The external token is invalid or expired."
        "403":
          description: The user's external account is not verified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Forbidden"
                message: "Account not verified with external provider. Please complete the verification process."
        "429":
          description: Too many requests. Please try again later.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Too Many Requests"
                message: "You have made too many requests in the past 5 minutes. Please try again later."
        "500":
          description: A server-side error occurred during authentication
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Internal Server Error"
                message: "An error occurred while processing your request. Please try again later."
  /register:
    post:
      summary: Register a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginData"
            example:
              username: "john.doe@gmail.com"
              password: "12345678"
      responses:
        "200":
          description: The user has been registered and we sent a verification email.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: Your account has been created and an verification email was sent to your email address. Please verify it before your first login.
        "400":
          description: The request payload is missing required fields
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
              example:
                error: "Bad Request"
                message: "The payload is missing some required fields."
                missingFields: ["email", "password"]
        "409":
          description: The provided email is invalid or already in use.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                error: "Conflict"
                message:  "The provided email is invalid or already in use. Please check and try again."
        "429":
          description: Too many requests. Please try again later.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Too Many Requests"
                message: "You have made too many requests in the past 5 minutes. Please try again later."
        "500":
          description: A server-side error occurred while registering.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                error: "Internal Server Error"
                message: "An error occurred while processing your request. Please try again later."
  /register/external/{provider}:
    post:
      summary: Register a new user account via an external provider
      parameters:
        - $ref: "#/components/parameters/ExternalProvider"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExternalLoginData"
      responses:
        "200":
          description: The user has been registered with the external provider.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Your account has been created with the external provider.
        "400":
          description: The request payload is missing required fields or is malformed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
              example:
                error: "Bad Request"
                message: "The payload is missing some required fields."
                missingFields: ["token"]
        "409":
          description: The provided email is invalid or already in use.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Conflict"
                message: "The provided email is invalid or already in use. Please check and try again."
        "429":
          description: Too many requests. Please try again later.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Too Many Requests"
                message: "You have made too many requests in the past 5 minutes. Please try again later."
        "500":
          description: A server-side error occurred while registering with the external provider.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Internal Server Error"
                message: "An error occurred while processing your request. Please try again later."
  /recovery/password:
    patch:
      summary: Reset the password of the account associated to the recovery token.
      parameters:
        - $ref: "#/components/parameters/RecoveryToken"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPassword"
            example:
              password: "12345678"
      responses:
        "200":
          description: The user's password has been changed and we sent an email.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: Your password has been successfully reset.
        "400":
          description: The request payload is missing required fields
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
              example:
                error: "Bad Request"
                message: "The payload is missing some required fields."
                missingFields: ["password"]
        "401":
          description: The recovery token is invalid or expired.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Unauthorized"
                message: "The recovery token is invalid or expired. Please request a new password reset."
        "404":
          description: The account associated with the recovery token could not be found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                error: "Not Found"
                message:  "No account was found associated with this recovery token."
        "429":
          description: Too many requests. Please try again later.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Too Many Requests"
                message: "You have made too many requests in the past 5 minutes. Please try again later."
        "500":
          description: A server-side error occurred while processing the password reset request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                error: "Internal Server Error"
                message: "An error occurred while processing your request. Please try again later."
  /verification/email:
    patch:
      summary: Verify the email of the account associated to the verification token.
      parameters:
        - $ref: "#/components/parameters/VerificationToken"
      responses:
        "200":
          description: The user's email has been verified and we sent an email.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: Your email has been successfully verified.
        "401":
          description: The verification token is invalid or expired.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Unauthorized"
                message: "The verification token is invalid or expired. Please request a new email verification."
        "404":
          description: The account associated with the verification token could not be found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                error: "Not Found"
                message:  "No account was found associated with this verification token."
        "429":
          description: Too many requests. Please try again later.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                error: "Too Many Requests"
                message: "You have made too many requests in the past 5 minutes. Please try again later."
        "500":
          description: A server-side error occurred while processing the email verification request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example: 
                error: "Internal Server Error"
                message: "An error occurred while processing your request. Please try again later."

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: A short error type identifier.
        message:
          type: string
          description: A detailed error message.
    BadRequestError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            missingFields:
              type: array
              items:
                type: string
              description: Fields missing from the request payload.
          example:
            error: "Bad Request"
            message: "The payload is missing some required fields."
            missingFields: ["email", "password"]
    UserLoginData:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        username: "john.doe@gmail.com"
        password: "12345678"
    ExternalLoginData:
      type: object
      properties:
        token:
          type: string
      example:
        token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTIzNDU2Nzg5MCIsIm5hbWUiOiJKb2huIERvZSJ9.Tm__Ymx-4FgWsd1zdb-WxMPojmK4Vmpx"
    UserPassword:
      type: object
      properties:
        password:
          type: string
      example:
        password: "12345678"
    UserAccessData:
      type: object
      properties:
        access_token: 
          type: string
        refresh_token: 
          type: string
        expire: 
          type: integer
  parameters:
    RecoveryToken:
      name: recovery_token
      in: query
      description: The value of the recovery token.
      required: true
      schema:
        type: string
    VerificationToken:
      name: verification_token
      in: query
      description: The value of the verification token.
      required: true
      schema:
        type: string
    ExternalProvider:
      name: provider
      in: path
      required: true
      description: The external provider to authenticate with
      schema:
        type: string
        enum: [google, facebook, apple]
      
    