services:
  betalink-auth-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: betalinkauth
      POSTGRES_PASSWORD: betalinkauth
      POSTGRES_DB: betalinkauth
    ports:
      - "5432:5432"
    volumes:
      - betalink-auth-db-data:/var/lib/postgresql/data

volumes:
  betalink-auth-db-data: